import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    ignores: [
      "node_modules/",
      "dist/",
      "build/",
      "*.min.js",
      "*.min.css",
      "vite.config.js",
      "postcss.config.mjs",
      "jsconfig.json",
      "package.json",
      "package-lock.json",
      ".git/",
      ".vscode/",
      ".idea/",
      ".DS_Store",
      "Thumbs.db",
      "*.log",
      "npm-debug.log*",
      ".env*",
    ],
  },
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        // Browser APIs
        console: "readonly",
        document: "readonly",
        window: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        PerformanceObserver: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        performance: "readonly",
        navigator: "readonly",
        Node: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        // Node.js globals (for Vite config)
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
        Buffer: "readonly",
        global: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      //   "no-console": "warn",
      "no-debugger": "error",
      "prefer-const": "error",
      "no-var": "error",
      eqeqeq: "error",
    },
  },
];
